{% set name = "pysm3" %}
{% set version = "3.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d09baac409a285d3f69a82066f249e787adf2daeeed54802357eb01aac409086

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
    - healpy
    - toml
    - numba
    - scipy
    - astropy-helpers
    - setuptools_scm
  run:
    - python >=3.6
    - healpy
    - toml
    - numba
    - scipy

test:
  imports:
    - pysm3
  requires:
    - pytest

about:
  home: https://github.com/healpy/pysm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Sky Model for Microwave and Submm experiments

  # The remaining entries in this section are optional, but recommended.
  doc_url: https://pysm3.readthedocs.io/

extra:
  recipe-maintainers:
    - zonca
