{% set name = "pysm3" %}
{% set version = "3.4.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4938ffdf845ddc1cb892782c42b401b6bd1d54b740913777be580e017bfa6ab8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
    - healpy
    - toml
    - numba
    - scipy
    - numpy
    - h5py
  run:
    - python >={{ python_min }}
    - healpy
    - h5py
    - toml
    - numba
    - scipy
    - numpy

test:
  imports:
    - pysm3
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-astropy

about:
  home: https://github.com/healpy/pysm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Sky Model for Microwave and Submm experiments

  # The remaining entries in this section are optional, but recommended.
  doc_url: https://pysm3.readthedocs.io/

extra:
  recipe-maintainers:
    - zonca
