{% set name = "pysm3" %}
{% set version = "3.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f3ae0f0a5e28295de7718e20ecc86f6b8b49eb4c59229e44e5c6c62a3a905431

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - healpy
    - toml
    - numba
    - scipy
    - numpy
  run:
    - python >={{ python_min }}
    - healpy
    - toml
    - numba
    - scipy
    - numpy

test:
  imports:
    - pysm3
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-astropy

about:
  home: https://github.com/healpy/pysm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python Sky Model for Microwave and Submm experiments

  # The remaining entries in this section are optional, but recommended.
  doc_url: https://pysm3.readthedocs.io/

extra:
  recipe-maintainers:
    - zonca
