{% set name = "pysm3" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc47d54b290fb19a510161550754341944bda1d63c30cea2d6aa00c46502957f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - healpy
    - toml
    - numba
    - scipy
    - setuptools_scm
    - numpy
  run:
    - python >=3.7
    - healpy
    - toml
    - numba
    - scipy
    - numpy

test:
  imports:
    - pysm3
  requires:
    - pytest

about:
  home: https://github.com/healpy/pysm
  license: BSD 3-clause
  license_family: MIT
  license_file: LICENSE
  summary: Python Sky Model for Microwave and Submm experiments

  # The remaining entries in this section are optional, but recommended.
  doc_url: https://pysm3.readthedocs.io/

extra:
  recipe-maintainers:
    - zonca
