{% set name = "pysm3" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c4b51683569fd630b820ec0e9f7af9e006c132ae804b97773238ba5b2128678

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - healpy
    - toml
    - numba
    - scipy
    - astropy-helpers
  run:
    - python >=3.6
    - healpy
    - toml
    - numba
    - scipy

test:
  imports:
    - pysm
  requires:
    - pytest

about:
  home: https://github.com/healpy/pysm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Sky Model for Microwave and Submm experiments

  # The remaining entries in this section are optional, but recommended.
  doc_url: https://pysm3.readthedocs.io/

extra:
  recipe-maintainers:
    - zonca
